export default {
  'devLog': false,
  'devMouseLog': false,
  'displayFunc': () => ({
    'displayHeight': null,
    'displayMotion': null,
    'displayOffsetH': null,
    'displayOffsetV': null,
    'displayOpacityDefault': null,
    'displayOpacityOnHover': null,
    'displaySampleLevel': null,
    'displayShow': null,
    'displaySide': null,
    'displayWidth': null,
  }),
  'displayHeight': '300px',
  'displayMotion': true,
  'displayOffsetH': 0,
  'displayOffsetV': -20,
  'displayOpacityDefault': 0.7,
  'displayOpacityOnHover': 0.2,
  'displaySampleLevel': 2,
  'displayShow': true,
  'displaySide': 'right',
  'displayWidth': '150px',
  'modelHeadPosH': 0.5,
  'modelHeadPosV': 0.618,
  'modelJsonPath': 'https://cdn.jsdelivr.net/npm/live2d-widget-model-shizuku/assets/shizuku.model.json',
  'z-index': 2333,
};
